site_name: Mine Opskrifter
site_description: En samling af mine yndlingsopskrifter
site_url: https://MSvante.github.io/opskrifter/
repo_url: https://github.com/MSvante/opskrifter
repo_name: GitHub
dev_addr: 127.0.0.1:4000

theme:
  name: material
  language: da
  palette:
    - scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Hjem: index.md
  - Hverdagsmad:
    - Pizza Bolo: hverdagsmad/pizza-bolo.md
    - Asiatisk Nudelsalat: hverdagsmad/asiatisk-nudelsalat.md
    - Kylling Pastasuppe: hverdagsmad/kylling-pastasuppe.md
    - Pasta Carbonara: hverdagsmad/pasta-carbonara.md
    - Fyldt Kyllingefilet med Feta: hverdagsmad/kyllingefilet-med-feta.md
    - Frikadeller: hverdagsmad/frikadeller.md
    - Flæskesteg: hverdagsmad/flæskesteg.md
    - Stegt Flæsk med Persillesovs: hverdagsmad/stegt-flæsk-med-persillesovs.md
    - Hakkebøf med Løg: hverdagsmad/hakkebof.md
    - Tarteletter: hverdagsmad/tarteletter.md
    - Biksemad: hverdagsmad/biksemad.md
    - Leverpostej: hverdagsmad/leverpostej.md
  - Vegetariske Retter:
    - Ratatouille: vegetar/ratatouille.md
    - Risotto med Svampe: vegetar/risotto-med-svampe.md
    - Grønkålssalat: vegetar/grønkålssalat.md
    - Ovnristede Rodfrugter: vegetar/rodfrugter-fra-ovnen.md
    - Grøntsagsgryde: vegetar/grøntsagsgryde.md
  - Fisk:
    - Stegt Rødspætte: fisk/stegt-rødspætte.md
    - Fiskefrikadeller: fisk/fiskefrikadeller.md
    - Fiskeboller i Karrysovs: fisk/fiskeboller.md
  - Forretter:
    - Klassisk Bruschetta: forretter/bruschetta.md
    - Hjemmelavet Hummus: forretter/hummus.md
    - Gravlaks: forretter/gravlaks.md
    - Blomkålssuppe: forretter/blomkålssuppe.md
    - Sild med Løg: forretter/sild-med-løg.md
  - Desserter & Kager:
    - Klassisk Chokoladekage: desserts/chokoladekage.md
    - Tiramisu: desserts/tiramisu.md
    - Rødgrød med Fløde: desserts/rødgrød-med-fløde.md
    - Pandekager: desserts/pandekager.md
    - Drømmekage: kager/drømmekage.md
    - Æblekage: kager/æblekage.md
    - Hindbærsnitter: kager/hindbærsnitter.md
    - Kringle: kager/kringle.md
    - Brunede Kartofler: kager/brunede-kartofler.md

plugins:
  - search:
      lang: da
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg